### ISSUE TITLE
cloning the repo, any artisan commands results in composer error code 255

### ISSUE THREAD

**Issue by rishabhrao076** [ably-labs/laravel-broadcast-app#15] opened 2023-03-10 11:09 UTC
doing a fresh clone and composer install results in an error

**Comment by sacOO7** [comment] 2023-03-10 11:26
Can you post the error here?

**Comment by sacOO7** [comment] 2023-03-10 11:27
Also post your current PHP and laravel version

**Comment by rishabhrao076** [comment] 2023-03-10 11:43
steps to recreate

my php version 8.2.2

1. git clone https://github.com/ably-labs/laravel-broadcast-app.git
2. composer install
```
> @php artisan package:discover --ansi
2023-03-10 11:07:52     Auth: no authentication parameters supplied

   Ably\Exceptions\AblyException

  No authentication parameters supplied

  at vendor/ably/ably-php/src/Auth.php:60
     56▕         } else if(!empty( $this->defaultAuthOptions->tokenDetails )) {
     57▕             Log::d( 'Auth: using token auth with supplied token only' );
     58▕         } else {
     59▕             Log::e( 'Auth: no authentication parameters supplied' );
  ➜  60▕             throw new AblyException ( 'No authentication parameters supplied', 40103, 401 );
     61▕         }
     62▕
     63▕         $this->tokenDetails = $this->defaultAuthOptions->tokenDetails;
     64▕     }

   Whoops\Exception\ErrorException

  Using ${var} in strings is deprecated, use {$var} instead

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): Whoops\Run->handleError()
#1 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): include()
#2 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
#14 [internal function]: Whoops\Run->handleException()
#15 {main}
  thrown in /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52

   Symfony\Component\ErrorHandler\Error\FatalError

  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): Whoops\Run->handleError()
#1 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): include()
#2 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/filp/whoops/src/Whoops/Run.php(370): NunoMaduro\Collision\Handler->handle()
#14 [internal function]: Whoops\Run->handleException()
#15 {main}
  thrown

  at vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
     48▕     }
     49▕
     50▕     protected function getCurrentBranch(string $directory): string
     51▕     {
  ➜  52▕         $branch = "'".trim(shell_exec("cd ${directory}; git branch | grep \\* | cut -d ' ' -f2"))."'";
     53▕
     54▕         if ($branch === "''") {
     55▕             $branch = 'current branch';
     56▕         }
PHP Fatal error:  Uncaught Whoops\Exception\ErrorException: Using ${var} in strings is deprecated, use {$var} instead in /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php:52
Stack trace:
#0 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): Whoops\Run->handleError()
#1 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(480): include()
#2 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#4 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(50): class_implements()
#5 [internal function]: Facade\Ignition\SolutionProviders\SolutionProviderRepository->Facade\Ignition\SolutionProviders\{closure}()
#6 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Arr.php(717): array_filter()
#7 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Collections/Collection.php(358): Illuminate\Support\Arr::where()
#8 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/SolutionProviderRepository.php(49): Illuminate\Support\Collection->filter()
#9 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php(36): Facade\Ignition\SolutionProviders\SolutionProviderRepository->getSolutionsForThrowable()
#10 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(244): NunoMaduro\Collision\Adapters\Laravel\IgnitionSolutionsRepository->getFromThrowable()
#11 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Writer.php(123): NunoMaduro\Collision\Writer->renderSolution()
#12 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Handler.php(39): NunoMaduro\Collision\Writer->write()
#13 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(72): NunoMaduro\Collision\Handler->handle()
#14 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(185): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->renderForConsole()
#15 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(171): Illuminate\Foundation\Bootstrap\HandleExceptions->renderForConsole()
#16 /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(209): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#17 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#18 {main}
  thrown in /home/rishabh/ably-test-app/laravel-broadcast-app/vendor/facade/ignition/src/SolutionProviders/MergeConflictSolutionProvider.php on line 52
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255
```

**Comment by sacOO7** [comment] 2023-03-10 12:04
Can you try https://github.com/ably-labs/laravel-broadcast-app#run-using-docker for the time being ? I will try to reproduce this on my local and will get back to you by tomorrow.

**Comment by rishabhrao076** [comment] 2023-03-10 12:11
Same Issue at RUN composer install with docker compose up method

**Comment by sacOO7** [comment] 2023-03-10 12:12
Ohkay 🤔... @qsdstefan can you take a look if available? 
btw, Is it the same exact log message? What's the php and laravel version

**Comment by sacOO7** [comment] 2023-03-10 12:14
Make sure you clear the local folder cache or clone the project in a different folder and run using docker there

**Comment by rishabhrao076** [comment] 2023-03-10 12:15
Its the same issue, PHP version is 8.2 , laravel version depends on the repository, cant say cause cant install

**Comment by sacOO7** [comment] 2023-03-10 12:24
@AndyTWF can you check what might be going wrong here. I think we support php 8.2 for ably-php

**Comment by AndyTWF** [comment] 2023-03-10 17:20
The root cause of this error is that no Ably key has been provided - this needs to be set in the `.env` file. After setting that, I don't get this error on PHP 8.1 or 8.2.

The second part is only triggered whilst trying to handle the first error. It looks like we need to update the dependencies (ignition) on this repo to fix that, I believe ably-php is fine.

**Comment by rishabhrao076** [comment] 2023-03-10 17:42
I think I did set the key, even still I believe that this type of error is expected on runtime and not while the dependencies are being installed. ably-php is running fine in a separate project of mine, I'm using the official laravel-broadcast [Here](https://github.com/ably/laravel-broadcaster) which itself is based on ably-php, my issue was limited to this demo

**Comment by AndyTWF** [comment] 2023-03-10 18:52
This demo app uses Ably's own implementation of the Laravel broadcaster - rather than the official Laravel one, and the error is occurring during Laravel package discovery. Setting `ABLY_KEY` in the `.env` should certainly fix it in the short-term.

I do agree though, that ideally this message shouldn't happen during package discovery, so I shall look into this.

**Comment by AndyTWF** [comment] 2023-03-13 13:30
Hi @rishabhrao076, I looked into this further for you. The reason the error arises is not something that can be easily avoided or deferred to runtime, unfortunately.

When performing the composer post-install scripts, composer actually boots the application (so this is, technically, runtime) to perform the `artisan package:discover` process, as part of the bootstrapmprocess it loads the broadcast channels from `routes/channels.php`.

By declaring channels (in any app, not just this one), Laravel requires an instance of the Broadcaster, which in turn means that we need to instantiate the `AblyRest` client from `ably-php`. Therefore, we need auth credentials to be present either in `.env` or cached config.

In theory, as long as you have a `.env` file with an ably key before you run `composer install`, everything should work fine. The readme specifies instructions in the wrong order here, so I'll get that updated.

Let me know if you have any other questions :)

**Comment by rishabhrao076** [comment] 2023-03-13 13:50
Thanks @AndyTWF I'll keep it in mind

**Comment by sacOO7** [comment] 2023-03-14 17:52
We have updated the doc as per #16. So, I am closing the issue. Please raise a new issue if you face any more problems.

**Closed by sacOO7** 2023-03-14 17:52 UTC
